apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: integration-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: integration-api
  template:
    metadata:
      labels:
        app: integration-api
    spec:
      containers:
        - name: integration-api
          image: yva19426/integration-api:latest
          ports:
            - containerPort: 8090
          env:
          - name: WORKFLOW_RELEASE
            value: blah